spring.application.name=app

# JWT
app.jwt.secret=5367566B59703373736739792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=86400000

# MYSQL - Aiven Cloud
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true